
# How much to bias the client data samples towards certain classes (non-IID data partitions)
bias: 0.7
# Parameters for local training
train_batch_size: 32
num_train_steps: 100

# Parameters for local validation
eval_batch_size: 32
num_eval_steps: 20

#Device settings
device: cuda
val_device: cuda
