version: '3.3'
services:
  client:
    environment:
      - GET_HOSTS_FROM=dns
    image: "electra-client:latest"
    runtime: nvidia
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data:/app/data
      - ./settings.yaml:/app/settings.yaml

networks:
  default:
    external:
      name: fedn_default

