version: '3.3'
services:
  client1:
    environment:
      - GET_HOSTS_FROM=dns
    image: "electra-client:latest"
    build:
      context: .
    working_dir: /app
    runtime: nvidia
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data:/app/data

networks:
  default:
    external:
      name: fedn_default

