version: '3.3'
services:
  client:
    environment:
      - GET_HOSTS_FROM=dns
    image: "electra-client:latest"
    runtime: nvidia
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in fedn-network.yaml"
    volumes:
      - ./data:/app/data
      - ./client_settings.yaml:/app/client_settings.yaml

    deploy:
        resources:
            reservations:
                devices:
                    - capabilities: [gpu]
